print ("Fun whit numbers bro")
print ("Please, use only enter numbers")
a= int(input("Please, enter the first number"))
b= int(input("Please, enter the second number"))
suma = (a+b)
resta = (a-b)
multiplicación = (a*b)
división = (a/b)
residuo = (a%b)
print ("The sum of your numbers is:" , suma)
print ("The difference of your numbers is:" , resta)
print ("The product of your numbers is:" , multiplicación)
print ("The integer division is:" , división)
print ("The remainder of integer division is:" , residuo)

print ("Tha, tha, thats, thats is all friends!")
